table Table
	lineageTag: b063d690-86e0-4c13-af98-e3ad841572d0

	column Administrative
		dataType: int64
		formatString: 0
		lineageTag: eef67871-91c1-4979-8939-9bed97d706b7
		summarizeBy: sum
		sourceColumn: Administrative

		annotation SummarizationSetBy = Automatic

	column Administrative_Duration
		dataType: double
		lineageTag: e7de3aff-dc49-4527-a8db-a40ff1f440d0
		summarizeBy: sum
		sourceColumn: Administrative_Duration

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Informational
		dataType: int64
		formatString: 0
		lineageTag: 978b60cc-39da-40c4-b8a1-fc45d3a3b93a
		summarizeBy: sum
		sourceColumn: Informational

		annotation SummarizationSetBy = Automatic

	column Informational_Duration
		dataType: double
		lineageTag: eed5c9b4-5488-4fde-b6f9-d8610779a000
		summarizeBy: sum
		sourceColumn: Informational_Duration

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column ProductRelated
		dataType: int64
		formatString: 0
		lineageTag: d083cea9-ed65-4e08-8a06-8d45752dc1b5
		summarizeBy: sum
		sourceColumn: ProductRelated

		annotation SummarizationSetBy = Automatic

	column ProductRelated_Duration
		dataType: double
		lineageTag: 243f3374-6ff6-4368-acf9-dd59174d9c0b
		summarizeBy: sum
		sourceColumn: ProductRelated_Duration

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column BounceRates
		dataType: double
		lineageTag: 8c55875d-dec7-4bb2-b1ec-b82222e5f085
		summarizeBy: sum
		sourceColumn: BounceRates

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column ExitRates
		dataType: double
		lineageTag: 4790eb80-520a-44f1-9e29-c76d043fe33d
		summarizeBy: sum
		sourceColumn: ExitRates

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column PageValues
		dataType: double
		lineageTag: 94c8071b-2721-426c-9125-7fcbde363df8
		summarizeBy: sum
		sourceColumn: PageValues

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column SpecialDay
		dataType: double
		lineageTag: 81caec72-43ef-4ad7-98a0-46f51907cdca
		summarizeBy: sum
		sourceColumn: SpecialDay

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Month
		dataType: string
		lineageTag: da4918d9-c0dc-43e9-8e46-0f959308e59c
		summarizeBy: none
		sourceColumn: Month

		annotation SummarizationSetBy = Automatic

	column OperatingSystems
		dataType: int64
		formatString: 0
		lineageTag: 2124f52b-5865-4b0a-a0bc-46e9ef0b16b9
		summarizeBy: sum
		sourceColumn: OperatingSystems

		annotation SummarizationSetBy = Automatic

	column Browser
		dataType: int64
		formatString: 0
		lineageTag: 71cb2d38-e4c1-405e-bd80-3f930ace3eb4
		summarizeBy: sum
		sourceColumn: Browser

		annotation SummarizationSetBy = Automatic

	column Region
		dataType: int64
		formatString: 0
		lineageTag: 563c332a-2af3-415b-9d5a-16018c27d4b4
		summarizeBy: sum
		sourceColumn: Region

		annotation SummarizationSetBy = Automatic

	column TrafficType
		dataType: int64
		formatString: 0
		lineageTag: c0af3a7b-286b-4e7f-a3aa-5465817f3101
		summarizeBy: sum
		sourceColumn: TrafficType

		annotation SummarizationSetBy = Automatic

	column VisitorType
		dataType: string
		lineageTag: e63dd977-8a8f-4a19-a0dd-1dcbef24c82a
		summarizeBy: none
		sourceColumn: VisitorType

		annotation SummarizationSetBy = Automatic

	column Weekend
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: d1e6e42b-305c-46e5-baf5-f8a196f90344
		summarizeBy: none
		sourceColumn: Weekend

		annotation SummarizationSetBy = Automatic

	column Revenue
		dataType: string
		lineageTag: 51103453-332d-40bb-9878-2bc6962bb7c5
		summarizeBy: none
		sourceColumn: Revenue

		annotation SummarizationSetBy = Automatic

	column Column1 = [Month]
		lineageTag: 2526ca66-0383-4e5a-8b20-a1623d31710a
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	partition Table = m
		mode: import
		source =
				let
				    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("tVhLb9QwEP4ve0bWzHg8to9IwKn0wOtSIQSoQr0UqRT4+4wn9sZu9pFNRbrOJpvE3zw+fzPpzc0Ody92oIPKQHQU9ACZdc9C0XHKIdpNDgC9QLBrekYgwuDbBGVc//zTpiqz1O93t4+/H+7v7n98+XT36+7x54P+9ubl1fvX5YmPV1e7zy9udrE8EMB5RWPK9fHyTVSOENljMYEqPOovKWeqxmAGRrDnXEjE0WPghVnhjFkf3n0crPLlftFdOUhiNpbHY/QuNMcdlKsxuYQYKVCsF17dft8ajRbQNsqUEYJL3rbqc9rHSs+mE7MRBgPM54LO1Yo1jh8ygJAGp/1szBBo33mMWwGNZWLRLsn2Uv5q6qcTv3S1eehPeLqItd0MMLtWeDetguCdUjylSjJlGQSSGn6kKDj6P2a8xeH69u8luRYjWD4Z6AkIOyCEjYGuq4uSLpsepQQd2HNMBcFJCgyQ8D+QO1msfcVv0eWJ3tNZn5tRZC5KtYlMVpGrXJHAbg6uSRkSsBNQz6sh6nTgCNhi4pk4TzFzmQByJamOt18fOsviJTExi2LnpTcpixoWL7rtL6kJokJHodBENSd7Tj4IDib4J6twU1qMUTSvMhUckcGWhct4CV5JQCTuJrMpQsd8SAso7qDi5YvLLN1jOlzMT3UFXsToZJGKJiGmQWzUtCgGyU6o001dRPaxiy6lDCplNBjRwFsJXFuqRNwBsTB+Kmv76lGpRP3CGnMpdazWUKKeGDYFzVAHkIY6sVa+LDQL7yTI1LksymJ/tohxGelEos9qZ5lWcEp8Sa2kLCHUcoFZJXOwdYzwSdk+ymR7MjfHiTtmTeksupSDQvNB1FYft/hrGYMZUM4JwikBOgtmK8THVnzVo/KprqZcPsu0bqpIpr69Flih8I1CdZvOwrTJQeRQF81aQpkGNkmTqe3lsg/A5DgkCNUI8ClqrUn1LCqv0biFSStEAq1JsjDn2aXZ1B9RdSWSYKfMxjR2IecBFLuxlmRUOUseouS92Rb9ZK0g5Oyij741+9rpY4TWh2lLFrNYZFBUT0G0JPvBrF5p1qamp4NZsasdQo3AceU0pNV6NpVa7e0XS8mCr+9k6DxjvVScLz0ZSV0HzJmivenofeyzhiY3097cfmvUei4RZsdp3g8w+GScgpm+j9VnOVyfZ2/W0vo4zHl32qtEPsHkde6Qk14nK3Mc8gKz0bS1pxt9K7vy6t7q4ZKvM1xrn4/BVbqeQJtKETvCzkUMMWWO7T8FrA3qXI8OJ3N7kI8m0/GAxJ3P65CeagAcQxpWQfMobI2plfi545/9S4vItT5iW+Ts/xZ+32SPpe5IBJ+38Cz+uetZDrQQo55clrEFN4ryMUQX941DO6LuffOJrw2b12N//gc=", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Administrative = _t, Administrative_Duration = _t, Informational = _t, Informational_Duration = _t, ProductRelated = _t, ProductRelated_Duration = _t, BounceRates = _t, ExitRates = _t, PageValues = _t, SpecialDay = _t, Month = _t, OperatingSystems = _t, Browser = _t, Region = _t, TrafficType = _t, VisitorType = _t, Weekend = _t, Revenue = _t]),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"Administrative", Int64.Type}, {"Administrative_Duration", type number}, {"Informational", Int64.Type}, {"Informational_Duration", type number}, {"ProductRelated", Int64.Type}, {"ProductRelated_Duration", type number}, {"BounceRates", type number}, {"ExitRates", type number}, {"PageValues", type number}, {"SpecialDay", type number}, {"Month", type text}, {"OperatingSystems", Int64.Type}, {"Browser", Int64.Type}, {"Region", Int64.Type}, {"TrafficType", Int64.Type}, {"VisitorType", type text}, {"Weekend", type logical}, {"Revenue", type text}})
				in
				    #"Changed Type"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

