table Table
	lineageTag: 019073b6-532d-41f0-93ae-ea094b202c9b

	column Product
		dataType: string
		lineageTag: ba1594aa-744a-4b1b-a889-ef05e5fa9c5c
		summarizeBy: none
		sourceColumn: Product

		annotation SummarizationSetBy = Automatic

	column Price
		dataType: int64
		formatString: 0
		lineageTag: aa9d234a-9ff5-4091-830e-ceed15ec2a35
		summarizeBy: sum
		sourceColumn: Price

		annotation SummarizationSetBy = Automatic

	partition Table = m
		mode: import
		source =
				let
				    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("i45Wck4sUtJRMlSK1YlWciotBrKNweywxDwg20gpNhYA", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Product = _t, Price = _t]),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"Product", type text}, {"Price", Int64.Type}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

